"""phase 4 correspondence

Revision ID: 0de4dd527cd1
Revises: be99533e9d98
Create Date: 2026-09-18 15:04:26.900051

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0de4dd527cd1'
down_revision: Union[str, None] = 'be99533e9d98'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('correspondence',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('program_id', sa.Integer(), nullable=False),
    sa.Column('faculty_id', sa.Integer(), nullable=True),
    sa.Column('document_id', sa.Integer(), nullable=True),
    sa.Column('direction', sa.String(length=20), nullable=False),
    sa.Column('subject', sa.String(length=500), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('occurred_at', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['faculty_id'], ['faculty.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['program_id'], ['programs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('correspondence', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_correspondence_faculty_id'), ['faculty_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_correspondence_program_id'), ['program_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('correspondence', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_correspondence_program_id'))
        batch_op.drop_index(batch_op.f('ix_correspondence_faculty_id'))

    op.drop_table('correspondence')
    # ### end Alembic commands ###
