"""phase 2 applicant profile

Revision ID: aa9d663039e5
Revises: fee31e2f9759
Create Date: 2026-09-18 14:23:25.206430

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aa9d663039e5'
down_revision: Union[str, None] = 'fee31e2f9759'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('applicant_profile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('target_degree', sa.String(length=100), nullable=True),
    sa.Column('research_interests', sa.Text(), nullable=True),
    sa.Column('keywords', sa.Text(), nullable=True),
    sa.Column('background_summary', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('applicant_profile')
    # ### end Alembic commands ###
