"""phase 3 experience and materials

Revision ID: be99533e9d98
Revises: aa9d663039e5
Create Date: 2026-09-18 14:47:12.299432

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'be99533e9d98'
down_revision: Union[str, None] = 'aa9d663039e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('education_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('institution', sa.String(length=300), nullable=False),
    sa.Column('degree', sa.String(length=200), nullable=True),
    sa.Column('field', sa.String(length=200), nullable=True),
    sa.Column('start_year', sa.Integer(), nullable=True),
    sa.Column('end_year', sa.Integer(), nullable=True),
    sa.Column('gpa', sa.String(length=20), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('experience_roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('organization', sa.String(length=300), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('experience_bullets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.Column('program_id', sa.Integer(), nullable=True),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('themes', sa.JSON(), nullable=False),
    sa.Column('evidence', sa.Text(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['program_id'], ['programs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['role_id'], ['experience_roles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('experience_bullets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_experience_bullets_program_id'), ['program_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_experience_bullets_role_id'), ['role_id'], unique=False)

    op.create_table('gap_dismissals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('program_id', sa.Integer(), nullable=False),
    sa.Column('theme', sa.String(length=300), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['program_id'], ['programs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('gap_dismissals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_gap_dismissals_program_id'), ['program_id'], unique=False)

    with op.batch_alter_table('applicant_profile', schema=None) as batch_op:
        batch_op.add_column(sa.Column('funding_needs', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('test_status', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('cv_emphasis_rules', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('applicant_profile', schema=None) as batch_op:
        batch_op.drop_column('cv_emphasis_rules')
        batch_op.drop_column('test_status')
        batch_op.drop_column('funding_needs')

    with op.batch_alter_table('gap_dismissals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_gap_dismissals_program_id'))

    op.drop_table('gap_dismissals')
    with op.batch_alter_table('experience_bullets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_experience_bullets_role_id'))
        batch_op.drop_index(batch_op.f('ix_experience_bullets_program_id'))

    op.drop_table('experience_bullets')
    op.drop_table('experience_roles')
    op.drop_table('education_entries')
    # ### end Alembic commands ###
