"""phase 1 core tables

Revision ID: fee31e2f9759
Revises: 62a33b7824c4
Create Date: 2026-09-18 14:01:48.824413

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fee31e2f9759'
down_revision: Union[str, None] = '62a33b7824c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('programs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('university', sa.String(length=300), nullable=False),
    sa.Column('department', sa.String(length=300), nullable=True),
    sa.Column('degree', sa.String(length=50), nullable=True),
    sa.Column('portal_url', sa.String(length=1000), nullable=True),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('date_added', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('deadlines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('program_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=40), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['program_id'], ['programs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('deadlines', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_deadlines_program_id'), ['program_id'], unique=False)

    op.create_table('faculty',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('program_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('research_areas', sa.Text(), nullable=True),
    sa.Column('homepage_url', sa.String(length=1000), nullable=True),
    sa.Column('contacted', sa.Boolean(), nullable=False),
    sa.Column('fit_summary', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['program_id'], ['programs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('faculty', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_faculty_program_id'), ['program_id'], unique=False)

    op.create_table('requirements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('program_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=40), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=40), nullable=False),
    sa.Column('needs_human_verification', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['program_id'], ['programs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('requirements', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_requirements_program_id'), ['program_id'], unique=False)

    op.create_table('stage_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('program_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('changed_at', sa.DateTime(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['program_id'], ['programs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('stage_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_stage_history_program_id'), ['program_id'], unique=False)

    op.create_table('documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('program_id', sa.Integer(), nullable=False),
    sa.Column('faculty_id', sa.Integer(), nullable=True),
    sa.Column('kind', sa.String(length=40), nullable=False),
    sa.Column('mode', sa.String(length=40), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('requires_review', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['faculty_id'], ['faculty.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['program_id'], ['programs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_documents_faculty_id'), ['faculty_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_documents_program_id'), ['program_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_documents_program_id'))
        batch_op.drop_index(batch_op.f('ix_documents_faculty_id'))

    op.drop_table('documents')
    with op.batch_alter_table('stage_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stage_history_program_id'))

    op.drop_table('stage_history')
    with op.batch_alter_table('requirements', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_requirements_program_id'))

    op.drop_table('requirements')
    with op.batch_alter_table('faculty', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_faculty_program_id'))

    op.drop_table('faculty')
    with op.batch_alter_table('deadlines', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_deadlines_program_id'))

    op.drop_table('deadlines')
    op.drop_table('programs')
    # ### end Alembic commands ###
